[package]
name = "logu-rs"
version = "0.1.0"
authors = ["liberatys"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8.0"
json = "0.12.4"
ace = "0.2.0"
